version: '3'

services:
  books:
    build:
      context: .
      dockerfile: Dockerfile.book-swap.chapter06
    ports:
      - "${BOOKSWAP_PORT}:${BOOKSWAP_PORT}" 
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d books" ]
      interval: 10s
      timeout: 5s
      retries: 5
